name: ${project.artifactId}
main: fr.k0bus.betterhalloween.Main
version: ${project.version}
api-version: 1.14
commands:
   bh:
      description: Main BetterHalloween plugins command
      usage: /bh <cmd>
permissions:
   bh.give:
      description: Give BH Items
   bh.items:
      description: List BH Items